default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: contact_manager_development

test:
  <<: *default
  database: contact_manager_test

production:
  <<: *default
  database: contact_manager_production
  username: contact_manager
  password: <%= ENV['CONTACT_MANAGER_DATABASE_PASSWORD'] %>
